### ISSUE TITLE
Does not work on Anki v2.1.26 for Mac

### ISSUE THREAD

**Issue by skjelbreia** [avanteGarbage/CelebrAnki#2]
Add-on does not work on Anki v2.1.26 for Mac.
Error that shows upon starting up Anki:

When loading 'Play a
celebrationcompletion sound when
you finish your deck':
Traceback (most recent call last):
File "aqt/addons.py" ,line 211,in
loadAddons
File "/Users/x/Library/Application
Support/Anki2/addons21/978869609/
__init__.py" ,line 3 ,in <module>
from aqt import gui_hooks,tr,
qconnect
ImportError: cannot import name 'tr'
from 'aqt' (/Applications/Anki.app/
Contents/MacOS/aqt/__init__.pyc)

If a fix could be applied I’d be grateful

**Comment by skjelbreia** [comment]
NVM managed to fix it by just removing “ tr,” from the third line of the python file. Seems to work fine now, thanks for the add-on
